openapi: 3.0.0
info:
  title: SwingNotes API
  version: 1.0.0
  description: API for managing personal notes and user authentication.
servers:
  - url: http://localhost:8080
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []

paths:
  /api/notes:
    get:
      summary: Get all notes
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Returns all notes for the authenticated user
    post:
      summary: Create a new note
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  maxLength: 50
                text:
                  type: string
                  maxLength: 300
              required:
                - title
                - text
      responses:
        '201':
          description: Note created

  /api/notes/{id}:
    put:
      summary: Update a note
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                text:
                  type: string
              required:
                - title
                - text
      responses:
        '200':
          description: Note updated

    delete:
      summary: Delete a note
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Note deleted

  /api/notes/search:
    get:
      summary: Search notes by title
      security:
        - bearerAuth: []
      parameters:
        - name: title
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Notes matching the title search
  /api/user/signup:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                firstname:
                  type: string
                surname:
                  type: string
                email:
                  type: string
                  format: email
                password:
                  type: string
              required:
                - firstname
                - surname
                - email
                - password
      responses:
        '201':
          description: Account successfully created
        '400':
          description: Bad request (missing fields or duplicate email)

  /api/user/login:
    post:
      summary: Login a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
              required:
                - email
                - password
      responses:
        '200':
          description: Login successful with token
        '401':
          description: Invalid credentials
